package config;
// Generated 02.03.2021 15:25:23 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * Client generated by hbm2java
 */
@Entity
@Table(name="client"
    ,catalog="vbn"
)
public class Client  implements java.io.Serializable {


     private int id;
     private User user;
     private String surname;
     private String name;
     private String patronymic;
     private String male;
     private String phone;
     private String date;
     private String email;
     private String regData;

    public Client() {
    }

	
    public Client(User user) {
        this.user = user;
    }
    public Client(User user, String surname, String name, String patronymic, String male, String phone, String date, String email, String regData) {
       this.user = user;
       this.surname = surname;
       this.name = name;
       this.patronymic = patronymic;
       this.male = male;
       this.phone = phone;
       this.date = date;
       this.email = email;
       this.regData = regData;
    }
   
     @GenericGenerator(name="generator", strategy="foreign", parameters=@Parameter(name="property", value="user"))@Id @GeneratedValue(generator="generator")

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

@OneToOne(fetch=FetchType.LAZY)@PrimaryKeyJoinColumn
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }

    
    @Column(name="Surname", length=45)
    public String getSurname() {
        return this.surname;
    }
    
    public void setSurname(String surname) {
        this.surname = surname;
    }

    
    @Column(name="Name", length=45)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="Patronymic", length=45)
    public String getPatronymic() {
        return this.patronymic;
    }
    
    public void setPatronymic(String patronymic) {
        this.patronymic = patronymic;
    }

    
    @Column(name="Male", length=45)
    public String getMale() {
        return this.male;
    }
    
    public void setMale(String male) {
        this.male = male;
    }

    
    @Column(name="Phone", length=45)
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }

    
    @Column(name="Date", length=45)
    public String getDate() {
        return this.date;
    }
    
    public void setDate(String date) {
        this.date = date;
    }

    
    @Column(name="Email", length=45)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="RegDATA", length=45)
    public String getRegData() {
        return this.regData;
    }
    
    public void setRegData(String regData) {
        this.regData = regData;
    }




}


