package config;
// Generated 02.03.2021 15:25:23 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Record generated by hbm2java
 */
@Entity
@Table(name="record"
    ,catalog="vbn"
)
public class Record  implements java.io.Serializable {


     private int id;
     private Service service;
     private User user;
     private String serviceData;
     private String recordcol;

    public Record() {
    }

	
    public Record(int id) {
        this.id = id;
    }
    public Record(int id, Service service, User user, String serviceData, String recordcol) {
       this.id = id;
       this.service = service;
       this.user = user;
       this.serviceData = serviceData;
       this.recordcol = recordcol;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Service")
    public Service getService() {
        return this.service;
    }
    
    public void setService(Service service) {
        this.service = service;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="User")
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }

    
    @Column(name="serviceDATA", length=100)
    public String getServiceData() {
        return this.serviceData;
    }
    
    public void setServiceData(String serviceData) {
        this.serviceData = serviceData;
    }

    
    @Column(name="recordcol", length=45)
    public String getRecordcol() {
        return this.recordcol;
    }
    
    public void setRecordcol(String recordcol) {
        this.recordcol = recordcol;
    }




}


