package config;
// Generated 02.03.2021 15:25:23 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Service generated by hbm2java
 */
@Entity
@Table(name="service"
    ,catalog="vbn"
)
public class Service  implements java.io.Serializable {


     private int id;
     private String name;
     private String price;
     private String duration;
     private String image;
     private String discount;
     private String description;
     private Set<Record> records = new HashSet<Record>(0);

    public Service() {
    }

	
    public Service(int id) {
        this.id = id;
    }
    public Service(int id, String name, String price, String duration, String image, String discount, String description, Set<Record> records) {
       this.id = id;
       this.name = name;
       this.price = price;
       this.duration = duration;
       this.image = image;
       this.discount = discount;
       this.description = description;
       this.records = records;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="Name", length=60)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="Price", length=60)
    public String getPrice() {
        return this.price;
    }
    
    public void setPrice(String price) {
        this.price = price;
    }

    
    @Column(name="Duration", length=100)
    public String getDuration() {
        return this.duration;
    }
    
    public void setDuration(String duration) {
        this.duration = duration;
    }

    
    @Column(name="Image", length=100)
    public String getImage() {
        return this.image;
    }
    
    public void setImage(String image) {
        this.image = image;
    }

    
    @Column(name="Discount", length=100)
    public String getDiscount() {
        return this.discount;
    }
    
    public void setDiscount(String discount) {
        this.discount = discount;
    }

    
    @Column(name="Description", length=100)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="service")
    public Set<Record> getRecords() {
        return this.records;
    }
    
    public void setRecords(Set<Record> records) {
        this.records = records;
    }




}


