package config;
// Generated 02.03.2021 15:25:23 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Inheritance;
import javax.persistence.InheritanceType;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name="user"
    ,catalog="vbn"
)
@Inheritance(strategy = InheritanceType.JOINED)
abstract public class User  implements java.io.Serializable {

     private int id;
     private Set<Record> records = new HashSet<Record>(0);

    public User() {
    }

	
    public User(int id) {
        this.id = id;
    }
    
   
     @Id 
     @GeneratedValue(strategy = GenerationType.IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }



@OneToMany(fetch=FetchType.LAZY, mappedBy="user")
    public Set<Record> getRecords() {
        return this.records;
    }
    
    public void setRecords(Set<Record> records) {
        this.records = records;
    }




}